# Generated by Django 3.2 on 2021-12-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuadro',
            name='autor',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cuadro',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
