# Generated by Django 3.2 on 2021-11-26 09:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cuadro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField(default=django.utils.timezone.now)),
                ('imagen', models.ImageField(upload_to='uploads/')),
                ('galeria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galerias.galeria')),
            ],
        ),
    ]
